### PR TITLE
Update config.

### PR DESCRIPTION
**Pull request by f1vefour**
This allows the Pi 2 to use the full 1 gigabyte of RAM.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Tested and confirmed working?

**Comment by f1vefour** [comment]
I don't have a Pi 2 so no I didn't test it. It came from popcornmix, it's okay to merge.

**Comment by CurlyMoo** [comment]
Good to include that in your commit :smile: Thanks!

**Comment by f1vefour** [comment]
The kernel was bumped to 3.18.6 also.

**Comment by f1vefour** [comment]
You should just trust me ;)

**Pull request merged**
