### PR TITLE
Fixing USB and adding framebuffer support for small lcd monitors.

### PR DESCRIPTION
**Pull request by f1vefour**
This USB option should be enabled by default.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
You have full access right :+1:

**Comment by CurlyMoo** [comment]
Just saying you don't need to do PR first.

**Comment by f1vefour** [comment]
I just like doing it this way.

**Comment by CurlyMoo** [comment]
Just spams our mailbox more :smile:

**Comment by f1vefour** [comment]
I will eventually re-pull the git but it's already setup for my clone.

**Pull request merged**
