### PR TITLE
Adding 3.18.y for Rpi

### PR DESCRIPTION
**Pull request by f1vefour**
Let me know if I missed anything

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you remove `config_deb_ctrlextra=Conflicts: xbian-package-kernel

**Comment by CurlyMoo** [comment]
Can you remove `config_deb_ctrlextra=Conflicts: xbian-package-kernel` from `config`. It's currently conflicting with itself.

**Comment by f1vefour** [comment]
done

**Comment by f1vefour** [comment]
Did it build?

**Comment by CurlyMoo** [comment]
Yes, and plain GPIO also worked fine. You tested the rest :)

**Comment by f1vefour** [comment]
Good news, I ordered a Pi 2 so I can test stuff locally on both versions soon.

**Pull request merged**
