### PR TITLE
Adding 3.18.y branch

### PR DESCRIPTION
**Pull request by f1vefour**
I added the initial commit for 3.18.y

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What about patches, `.config` and such?

**Comment by f1vefour** [comment]
I was making sure this is what you wanted. I'm working on the configuration now, I will close this request and do a full request when I'm finished.

**Comment by CurlyMoo** [comment]
:+1:

**Comment by anaconda** [comment]
Patches for 3.18 are available at:
http://ck.kolivas.org/patches/3.0/3.18/3.18-ck1/patch-3.18-ck1.bz2 (bfs, other small changes)
http://algo.ing.unimo.it/people/paolo/disk_sched/sources.php (bfq) - this seems offline right now.

**Comment by CurlyMoo** [comment]
Are these your patches?

**Comment by anaconda** [comment]
These are the (completely) external patches we're applying to the Pi kernel:
https://github.com/xbianonpi/xbian-package-kernel/tree/master/patches/rpi and
https://github.com/xbianonpi/xbian-package-kernel/tree/master/patches/rpi-3.17.y (although I see for 3.17 mk01 is only applying the bfs patch instead of the whole ck patch set)

**Comment by f1vefour** [comment]
Thanks anaconda, I added the latest bfs patch and it applies cleanly and builds. I'm not sure we need the additional ck patches?

Do you have the latest bfq patch since it's offline?

**Comment by anaconda** [comment]
The small one I was interested in seems merged in the bfs patch (probably already was in 3.16?), so I'm okay if we only apply that.

It seems there's a mirror for bfq: http://repo-ck.com/source/mirror/
Let's double check when the official source comes back though.

**Comment by f1vefour** [comment]
I found them, and thanks mate. The three patch apply cleanly. Now I'm working on the last patch, lz4...after this the pull request will be ready.

**Pull request closed without merging**
